// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Coupon Manager",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "Coupon Manager",
            targets: ["AppModule"],
            bundleIdentifier: "com.seungsub.CouponManager",
            teamIdentifier: "MWF8UC94P5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "We need to scan QR codes")
            ],
            appCategory: .lifestyle,
            additionalInfoPlistContentFilePath: "MoreInfo.plist"
        )
    ],
    dependencies: [
        .package(url: "https://github.com/google/GoogleSignIn-iOS", "7.0.0"..<"8.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "GoogleSignIn", package: "googlesignin-ios"),
                .product(name: "GoogleSignInSwift", package: "googlesignin-ios")
            ],
            path: ".",
            exclude: ["./MoreInfo.plist"]
        )
    ]
)